### ISSUE TITLE
two cities, same name

### ISSUE THREAD

**Issue by scriptor-pro** [eoin-barr/weatherme#5]
Let's say I want to know the weather in Paris, Texas - how can I choose this particular city and not receive the weather for Paris, capital city of France. There is many cities named Springfield in the USA how to know the weather of the ones not in Illinois ?

**Comment by cosmosified** [comment]
or duluth ..
(duluth, MN && Duluth, GA)

**Comment by eoin-barr** [comment]
Great spot ! Will implement a fix for this
